apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgpt
  namespace: argocd
spec:
  project: default
  source:
    chart: k8sgpt-operator
    repoURL: https://charts.k8sgpt.ai/
    targetRevision: 0.0.17
    helm:
      values: |
        serviceMonitor:
          enabled: true
        GrafanaDashboard:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true